name: Trigger Cypress Tests

on:
  push:
    branches:
      -

jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            data-collection:
              - 'src/pages/components/Tabs/DataCollectionTab/**'
            evidence:
              - 'src/pages/components/Tabs/EvidenceTab/**'
            contract:
              - 'src/pages/contract-creation/**'
            map:
              - 'src/pages/map/**'

      - if: steps.changes.outputs.data-collection == 'true'
        uses: ./.github/workflows/main.yml
        with:
          test-group: "Data-Collection"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.changes.outputs.evidence == 'true'
        uses: ./.github/workflows/main.yml
        with:
          test-group: "Evidence"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.changes.outputs.contract == 'true'
        uses: ./.github/workflows/main.yml
        with:
          test-group: "Contract"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.changes.outputs.map == 'true'
        uses: ./.github/workflows/main.yml
        with:
          test-group: "Map"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
